# Site settings
author: Hailey Bongo
title: Hailey's Blog
header-img: img/home-bg.png
email: haileyebongo@gmail.com
copyright_name: Hailey Bongo
description: > # this means to ignore newlines until "baseurl:"
  My journey into software engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  haileybongo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
